# Generated by Django 4.1.3 on 2022-11-29 12:23

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63, unique=True)),
                ("author", models.CharField(max_length=63)),
                (
                    "cover",
                    models.CharField(
                        choices=[("H", "Hard"), ("S", "Soft")], max_length=4
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        validators=[books.models.validate_positive]
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[books.models.validate_positive],
                    ),
                ),
            ],
        ),
    ]
